url: "https://captnemo.in" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/emoji-every-day" # the subpath of your site, e.g. /blog
title: "Emoji Every Day" # the name of your site, e.g. ACME Corp.
exclude:
  - vendor
  - test.py